[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/klipper/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    192.168.0.0/16
    127.0.0.0/8
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail
persistent_files:
    config.json

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
optional_deps: scripts/system-dependencies.json
primary_branch: master
managed_services: KlipperScreen

[update_manager katapult]
type: git_repo
path: ~/katapult
origin: https://github.com/Arksine/katapult.git
is_system_service: False

[update_manager chopper_resonance_tuner]
type: git_repo
path: ~/chopper-resonance-tuner
origin: https://github.com/MRX8024/chopper-resonance-tuner.git
primary_branch: main
managed_services: klipper

[update_manager voron_config]
type: git_repo
path: ~/printer_data/config
origin: https://github.com/Lomonosow/voron.git
primary_branch: main
managed_services: klipper moonraker KlipperScreen crowsnest

[update_manager Klippain-ShakeTune]
type: git_repo
path: ~/klippain_shaketune
origin: https://github.com/Frix-x/klippain-shaketune.git
virtualenv: ~/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper
